language: ruby
rvm:
- 2.1.5
bundler_args: "--without kitchen_vagrant"
before_install:
- openssl aes-256-cbc -K $encrypted_6bb471548987_key -iv $encrypted_6bb471548987_iv
  -in secret_keys.tar.enc -out secret_keys.tar -d
- tar xf .travis/secret_keys.tar -C .travis
- mv .travis/travis_rsa ~/.ssh/id_rsa
script:
- bundle exec rubocop
- bundle exec kitchen test -d always
notifications:
  slack:
    secure: lITD1lbDJ9n3/9L8Jw5332FiEbpsZ/+SfMgv7sKXqyubwRcfCjyEdlMFHp3/JPtVSoVO8Wg5fD8vFKEtS6cEbAtETs4YXwJ0eFd5K4waz9c1MxPLLSkJY7b+X2qWdHx3gSoA1cirMpvSHOGHudPoQEvhtA+6dGTRo/6nS7JKnRE=
env:
  global:
  - KITCHEN_YAML=.kitchen.cloud.yml
  - secure: yJbD3s6lpObmFq/AHCSKEqI8uzBonWSNCV6n8keVLYz0WkfEWtZ1P0d2Fa5PEUu1fxvhVT5LKDF8U60VPmq7eVbz0P0z4MybI/v/NoQDx2rt1ky53S298/FkKEPqzZ/LZ74IP4CvXQenSHwbZXVFVLjDec1NTntkNG1j8KHHxEc=
  - secure: s2FNP0T2DHDF7Oi4ayzpzMZC/1bmKhJyyu7AOPRGEkUJwCTIY0m0kNJuEENdfgHGU1SIPp4Kk4ytGxXVU5l82z1CuC25FCWpASyAWvL2mdj18m6BgfI5OY0PcPEt1VqQDhAocrpvIEjNDRO6T9iezafTdEDq9QRUtZ8+QjRUx8I=
